import { createOctokitClient } from "./github";
import type { CodeSuggestion } from "@/module/ai/types/suggestion";

interface ReviewComment {
  path: string;
  line: number;
  startLine?: number;
  body: string;
}

/**
 * PR Review API로 인라인 suggestion 코멘트를 포스팅한다.
 * 전체 리뷰 요약은 review body에, 개별 제안은 inline comment로.
 */
export async function postPRReviewWithSuggestions(
  token: string,
  owner: string,
  repo: string,
  prNumber: number,
  reviewBody: string,
  suggestions: CodeSuggestion[],
  headSha: string,
): Promise<void> {
  const octokit = createOctokitClient(token);

  const comments: ReviewComment[] = suggestions.map((s) => {
    const beforeLineCount = s.before.split("\n").length;
    const comment: ReviewComment = {
      path: s.file,
      line: s.line + beforeLineCount - 1,
      body: formatSuggestionComment(s),
    };
    if (beforeLineCount > 1) {
      comment.startLine = s.line;
    }
    return comment;
  });

  await octokit.rest.pulls.createReview({
    owner,
    repo,
    pull_number: prNumber,
    commit_id: headSha,
    body: `## AI Code Review\n\n${reviewBody}\n\n---\n*Generated by HReviewer*`,
    event: "COMMENT",
    comments: comments.map(({ startLine, ...c }) => ({
      ...c,
      ...(startLine ? { start_line: startLine } : {}),
    })),
  });
}

function formatSuggestionComment(suggestion: CodeSuggestion): string {
  const severityEmoji = {
    CRITICAL: "🚨",
    WARNING: "⚠️",
    SUGGESTION: "💡",
    INFO: "ℹ️",
  }[suggestion.severity];

  return `${severityEmoji} **${suggestion.severity}**: ${suggestion.explanation}

\`\`\`suggestion
${suggestion.after}
\`\`\``;
}
