import { createOctokitClient } from "./github";
import type { CodeSuggestion, StructuredIssue } from "@/module/ai";
import { CATEGORY_EMOJI, SEVERITY_EMOJI } from "@/module/ai";

interface ReviewComment {
  path: string;
  line: number;
  startLine?: number;
  body: string;
}

interface PostPRReviewParams {
  token: string;
  owner: string;
  repo: string;
  prNumber: number;
  reviewBody: string;
  suggestions: CodeSuggestion[];
  issues: StructuredIssue[];
  headSha: string;
}

/**
 * PR Review API로 인라인 suggestion 코멘트를 포스팅한다.
 * 전체 리뷰 요약은 review body에, 개별 제안은 inline comment로.
 *
 * ⚠️ 분리 포스팅 전략:
 * inline issues를 suggestions와 같은 createReview() 호출에 넣으면,
 * AI가 diff 범위 밖 line number를 생성한 경우 전체 호출이 422로 실패하여 정상 suggestions까지 손실된다.
 * suggestions는 before 필드로 diff 정합성을 검증할 수 있지만, issues는 검증 수단이 없다.
 * 따라서 suggestions 먼저 포스팅 → issues 별도 포스팅(실패 허용) 전략을 사용한다.
 */
export async function postPRReviewWithSuggestions(params: PostPRReviewParams): Promise<void> {
  const { token, owner, repo, prNumber, reviewBody, suggestions, issues, headSha } = params;
  const octokit = createOctokitClient(token);

  // suggestion comments
  const suggestionComments: ReviewComment[] = suggestions.map((s) => {
    const beforeLineCount = s.before.split("\n").length;
    const comment: ReviewComment = {
      path: s.file,
      line: s.line + beforeLineCount - 1,
      body: formatSuggestionComment(s),
    };
    if (beforeLineCount > 1) {
      comment.startLine = s.line;
    }
    return comment;
  });

  // issue comments (file+line 둘 다 있는 issues만 inline comment로)
  // file-level issues (line: null)는 review body 테이블에 포함됨
  // ⚠️ type predicate 사용 — plain .filter()는 TypeScript narrowing 불가
  const inlineIssues = issues.filter(
    (i): i is StructuredIssue & { file: string; line: number } =>
      i.file !== null && i.line !== null
  );
  const issueComments: ReviewComment[] = inlineIssues.map((i) => ({
    path: i.file,
    line: i.line,
    body: formatIssueComment(i),
  }));

  // 1차 호출: suggestions + review body (summary + general issues 테이블)
  await octokit.rest.pulls.createReview({
    owner,
    repo,
    pull_number: prNumber,
    commit_id: headSha,
    body: `## AI Code Review\n\n${reviewBody}\n\n---\n*Generated by HReviewer*`,
    event: "COMMENT",
    comments: suggestionComments.map(({ startLine, ...c }) => ({
      ...c,
      ...(startLine ? { start_line: startLine } : {}),
    })),
  });

  // 2차 호출: inline issues — 실패해도 suggestions에 영향 없음
  // ⚠️ line-specific issues(file+line)는 review body에 미포함 — 2차 호출 실패 시 유실됨
  // general issues(line: null)만 review body 테이블에 포함되어 보존됨
  if (issueComments.length > 0) {
    try {
      await octokit.rest.pulls.createReview({
        owner,
        repo,
        pull_number: prNumber,
        commit_id: headSha,
        // body 필드 생략 — body: "" 사용 시 GitHub PR Conversation 탭에 빈 review entry 생성됨
        event: "COMMENT",
        // issueComments는 startLine이 없으므로 (single-line만) 직접 전달
        comments: issueComments.map(({ body, path, line }) => ({
          path,
          line,
          body,
        })),
      });
    } catch (error) {
      console.warn("Inline issue comments failed (suggestions were posted successfully):", error);
    }
  }
}

function formatSuggestionComment(suggestion: CodeSuggestion): string {
  return `${SEVERITY_EMOJI[suggestion.severity]} **${suggestion.severity}**: ${suggestion.explanation}

\`\`\`suggestion
${suggestion.after}
\`\`\``;
}

function formatIssueComment(issue: StructuredIssue): string {
  return `${CATEGORY_EMOJI[issue.category]} ${SEVERITY_EMOJI[issue.severity]} **${issue.severity}** | ${issue.category}\n\n${issue.description}`;
}
