import { describe, expect, it } from "vitest";

import {
  assertGithubArtifactBodyBudget,
  buildGithubArtifactBody,
  GITHUB_ARTIFACT_BODY_BUDGET_BYTES,
  GithubArtifactBodyBudgetError,
} from "./github-artifact-body";

describe("buildGithubArtifactBody", () => {
  const marker = "<!-- hreviewer:review:review-1:main -->";

  it("builds title, canonical content, marker, and footer exactly once", () => {
    const body = buildGithubArtifactBody({
      content: "Canonical review",
      marker,
      title: "AI Code Review",
    });

    expect(body).toBe(
      `## AI Code Review\n\nCanonical review\n\n${marker}\n\n---\n*Generated by HReviewer*`,
    );
    expect(body.match(/hreviewer:review/g)).toHaveLength(1);
  });

  it("rejects prebuilt content that already contains the exact marker", () => {
    expect(() =>
      buildGithubArtifactBody({ content: `Review\n${marker}`, marker }),
    ).toThrow("already contains its marker");
  });
});

describe("assertGithubArtifactBodyBudget", () => {
  it("accepts exactly 60,000 UTF-8 bytes", () => {
    expect(() =>
      assertGithubArtifactBodyBudget({
        body: "a".repeat(GITHUB_ARTIFACT_BODY_BUDGET_BYTES),
      }),
    ).not.toThrow();
  });

  it("rejects 60,001 UTF-8 bytes without truncating", () => {
    const body = "a".repeat(GITHUB_ARTIFACT_BODY_BUDGET_BYTES + 1);

    expect(() => assertGithubArtifactBodyBudget({ body })).toThrow(
      GithubArtifactBodyBudgetError,
    );
    expect(body).toHaveLength(GITHUB_ARTIFACT_BODY_BUDGET_BYTES + 1);
  });
});
