import { describe, expect, it } from "vitest";

import {
  assertGithubArtifactBodyBudget,
  buildGithubArtifactBody,
  GITHUB_ARTIFACT_BODY_BUDGET_BYTES,
} from "./github-artifact-body";

describe("GitHub artifact body", () => {
  it("assembles title, wrapper-free content, marker, and footer in order", () => {
    expect(
      buildGithubArtifactBody({
        content: "Canonical content",
        marker: "<!-- marker -->",
        title: "AI Code Review",
      }),
    ).toBe(
      "## AI Code Review\n\nCanonical content\n\n<!-- marker -->\n\n---\n*Generated by HReviewer*",
    );
  });

  it("rejects content that was already wrapped with the exact marker", () => {
    expect(() =>
      buildGithubArtifactBody({
        content: "Canonical content\n<!-- marker -->",
        marker: "<!-- marker -->",
      }),
    ).toThrow("already contains its marker");
  });

  it("allows exactly 60,000 UTF-8 bytes and rejects 60,001", () => {
    assertGithubArtifactBodyBudget({
      body: "a".repeat(GITHUB_ARTIFACT_BODY_BUDGET_BYTES),
    });
    expect(() =>
      assertGithubArtifactBodyBudget({
        body: `가${"a".repeat(GITHUB_ARTIFACT_BODY_BUDGET_BYTES - 2)}`,
      }),
    ).toThrow("60,001 bytes");
  });
});
