export const GITHUB_ARTIFACT_BODY_BUDGET_BYTES = 60_000;

const GENERATED_BY_FOOTER = "---\n*Generated by HReviewer*";

export class GithubArtifactBodyCompositionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GithubArtifactBodyCompositionError";
  }
}

export class GithubArtifactBodyBudgetError extends Error {
  constructor(readonly actualBytes: number) {
    super(
      `GitHub artifact body is ${actualBytes} bytes; the limit is ${GITHUB_ARTIFACT_BODY_BUDGET_BYTES}`,
    );
    this.name = "GithubArtifactBodyBudgetError";
  }
}

export function buildGithubArtifactBody(input: {
  content: string;
  marker: string;
  title?: string;
}): string {
  const content = input.content.trim();
  const marker = input.marker.trim();
  const title = input.title?.trim();

  if (content.length === 0) {
    throw new GithubArtifactBodyCompositionError(
      "GitHub artifact content must not be empty",
    );
  }
  if (marker.length === 0) {
    throw new GithubArtifactBodyCompositionError(
      "GitHub artifact marker must not be empty",
    );
  }
  if (content.includes(marker)) {
    throw new GithubArtifactBodyCompositionError(
      "GitHub artifact content already contains its marker",
    );
  }

  return [title ? `## ${title}` : null, content, marker, GENERATED_BY_FOOTER]
    .filter((part): part is string => part !== null)
    .join("\n\n");
}

export function assertGithubArtifactBodyBudget(input: {
  body: string;
}): void {
  const actualBytes = new TextEncoder().encode(input.body).byteLength;
  if (actualBytes > GITHUB_ARTIFACT_BODY_BUDGET_BYTES) {
    throw new GithubArtifactBodyBudgetError(actualBytes);
  }
}
