export const GITHUB_ARTIFACT_BODY_BUDGET_BYTES = 60_000;

const GENERATED_FOOTER = "---\n*Generated by HReviewer*";

export class GithubArtifactBodyBudgetError extends Error {
  constructor(byteLength: number) {
    super(
      `GitHub artifact body is ${byteLength.toLocaleString("en-US")} bytes; the limit is ${GITHUB_ARTIFACT_BODY_BUDGET_BYTES.toLocaleString("en-US")} bytes`,
    );
    this.name = "GithubArtifactBodyBudgetError";
  }
}

export function assertGithubArtifactBodyBudget(input: {
  body: string;
}): void {
  const byteLength = new TextEncoder().encode(input.body).byteLength;
  if (byteLength > GITHUB_ARTIFACT_BODY_BUDGET_BYTES) {
    throw new GithubArtifactBodyBudgetError(byteLength);
  }
}

export function buildGithubArtifactBody(input: {
  content: string;
  marker: string;
  title?: string;
}): string {
  if (input.content.includes(input.marker)) {
    throw new Error("GitHub artifact content already contains its marker");
  }

  const body = [
    input.title ? `## ${input.title}` : null,
    input.content,
    input.marker,
    GENERATED_FOOTER,
  ]
    .filter((part): part is string => part !== null)
    .join("\n\n");

  assertGithubArtifactBodyBudget({ body });
  return body;
}
