import { beforeEach, describe, expect, it, vi } from "vitest";

const octokitMocks = vi.hoisted(() => ({
  pullsGet: vi.fn(),
  reposGetCollaboratorPermissionLevel: vi.fn(),
  reposGetCommit: vi.fn(),
  reposGetContent: vi.fn(),
  gitGetTree: vi.fn(),
  issuesCreateComment: vi.fn(),
}));

vi.mock("octokit", () => ({
  Octokit: class MockOctokit {
    rest = {
      pulls: { get: octokitMocks.pullsGet },
      repos: {
        getCollaboratorPermissionLevel:
          octokitMocks.reposGetCollaboratorPermissionLevel,
        getCommit: octokitMocks.reposGetCommit,
        getContent: octokitMocks.reposGetContent,
      },
      git: { getTree: octokitMocks.gitGetTree },
      issues: { createComment: octokitMocks.issuesCreateComment },
    };
  },
}));

vi.mock("@/lib/server-utils", () => ({
  requireAuthSession: vi.fn(),
}));

vi.mock("@/lib/db", () => ({
  default: {
    account: { findFirst: vi.fn() },
  },
}));

import {
  canRunReviewCommand,
  getFileContent,
  getPullRequestDiff,
  getPullRequestHeadInfo,
  getPullRequestSnapshot,
  getRepositoryPermissionForUser,
  getRepositoryFileTree,
  postReviewComment,
} from "./github";

describe("postReviewComment", () => {
  it("posts one deterministic body and returns the API artifact", async () => {
    octokitMocks.issuesCreateComment.mockResolvedValue({
      data: { id: 71, created_at: "2026-08-26T00:00:00Z" },
    });

    await expect(
      postReviewComment({
        token: "token",
        owner: "octo",
        repo: "sample",
        prNumber: 42,
        content: "Canonical review",
        marker: "<!-- hreviewer:review:review_1:main -->",
        title: "AI Code Review",
      }),
    ).resolves.toEqual({
      id: "71",
      kind: "issue-comment",
      commitId: null,
      postedAt: new Date("2026-08-26T00:00:00Z"),
    });

    expect(octokitMocks.issuesCreateComment).toHaveBeenCalledWith(
      expect.objectContaining({
        body: "## AI Code Review\n\nCanonical review\n\n<!-- hreviewer:review:review_1:main -->\n\n---\n*Generated by HReviewer*",
        request: { signal: expect.any(AbortSignal) },
      }),
    );
  });
});

type PullRequestOverrides = {
  headSha?: string;
  baseSha?: string;
  updatedAt?: string;
  headRepository?: { owner: string; repo: string } | null;
  state?: string;
  merged?: boolean;
};

function createPullRequest(overrides: PullRequestOverrides = {}) {
  const headRepository = overrides.headRepository === undefined
    ? { owner: "head-owner", repo: "head-repo" }
    : overrides.headRepository;

  return {
    title: "Stable PR",
    html_url: "https://github.com/base-owner/base-repo/pull/7",
    body: "Description",
    additions: 4,
    deletions: 2,
    changed_files: 1,
    updated_at: overrides.updatedAt ?? "2026-08-04T00:00:00Z",
    base: { sha: overrides.baseSha ?? "base-sha" },
    head: {
      sha: overrides.headSha ?? "head-sha",
      ref: "feature-branch",
      repo: headRepository
          ? {
            name: headRepository.repo,
            owner: { login: headRepository.owner },
            full_name: `${headRepository.owner}/${headRepository.repo}`,
          }
        : null,
    },
    state: overrides.state ?? "open",
    merged: overrides.merged ?? false,
  };
}

function queuePullRequestAttempt(
  before: ReturnType<typeof createPullRequest>,
  after: ReturnType<typeof createPullRequest>,
  diff = "diff body",
): void {
  octokitMocks.pullsGet
    .mockResolvedValueOnce({ data: before })
    .mockResolvedValueOnce({ data: diff })
    .mockResolvedValueOnce({ data: after });
}

describe("repository command permission", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it.each([
    ["admin", "admin"],
    ["write", "write"],
    ["read", "read"],
    ["none", "none"],
    ["maintain", "write"],
    ["triage", "read"],
  ] as const)(
    "normalizes the %s role through GitHub's legacy %s permission",
    async (roleName, permission) => {
      octokitMocks.reposGetCollaboratorPermissionLevel.mockResolvedValue({
        data: { permission, role_name: roleName },
      });

      await expect(
        getRepositoryPermissionForUser({
          token: "token",
          owner: "octo",
          repo: "sample",
          username: "contributor",
        }),
      ).resolves.toBe(permission);
      expect(
        octokitMocks.reposGetCollaboratorPermissionLevel,
      ).toHaveBeenCalledWith({
        owner: "octo",
        repo: "sample",
        username: "contributor",
      });
    },
  );

  it("treats a 404 as no repository permission", async () => {
    octokitMocks.reposGetCollaboratorPermissionLevel.mockRejectedValue({
      status: 404,
    });

    await expect(
      getRepositoryPermissionForUser({
        token: "token",
        owner: "octo",
        repo: "sample",
        username: "outsider",
      }),
    ).resolves.toBe("none");
  });

  it.each([401, 403, 429, 500])(
    "propagates a transient or authentication HTTP %s error",
    async (status) => {
      const error = { status };
      octokitMocks.reposGetCollaboratorPermissionLevel.mockRejectedValue(error);

      await expect(
        getRepositoryPermissionForUser({
          token: "token",
          owner: "octo",
          repo: "sample",
          username: "contributor",
        }),
      ).rejects.toBe(error);
    },
  );

  it("propagates network failures", async () => {
    const error = new Error("network unavailable");
    octokitMocks.reposGetCollaboratorPermissionLevel.mockRejectedValue(error);

    await expect(
      getRepositoryPermissionForUser({
        token: "token",
        owner: "octo",
        repo: "sample",
        username: "contributor",
      }),
    ).rejects.toBe(error);
  });

  it("rejects an unexpected permission instead of silently authorizing it", async () => {
    octokitMocks.reposGetCollaboratorPermissionLevel.mockResolvedValue({
      data: { permission: "custom", role_name: "custom" },
    });

    await expect(
      getRepositoryPermissionForUser({
        token: "token",
        owner: "octo",
        repo: "sample",
        username: "contributor",
      }),
    ).rejects.toThrow("unsupported repository permission");
  });

  it.each([
    ["admin", true],
    ["write", true],
    ["read", false],
    ["none", false],
  ] as const)("authorizes %s permission: %s", (permission, expected) => {
    expect(canRunReviewCommand(permission)).toBe(expected);
  });
});

describe("getPullRequestDiff", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns metadata from the after read when the first snapshot is stable", async () => {
    const pullRequest = createPullRequest();
    queuePullRequestAttempt(pullRequest, pullRequest);

    const result = await getPullRequestDiff({
      token: "token",
      owner: "base-owner",
      repo: "base-repo",
      prNumber: 7,
    });

    expect(result).toMatchObject({
      diff: "diff body",
      baseSha: "base-sha",
      headSha: "head-sha",
      headRepository: { owner: "head-owner", repo: "head-repo" },
    });
    expect(octokitMocks.pullsGet).toHaveBeenCalledTimes(3);
    expect(octokitMocks.pullsGet.mock.calls[1][0]).toMatchObject({
      mediaType: { format: "diff" },
    });
    expect(octokitMocks.pullsGet.mock.calls[0][0]).not.toHaveProperty("mediaType");
    expect(octokitMocks.pullsGet.mock.calls[2][0]).not.toHaveProperty("mediaType");
  });

  it.each([
    ["head SHA", { headSha: "changed-head" }],
    ["base SHA", { baseSha: "changed-base" }],
    ["updated_at", { updatedAt: "2026-08-04T00:00:01Z" }],
  ] as const)(
    "discards a snapshot when only %s changes and returns the stable retry",
    async (_field, changedAfterOverrides) => {
      queuePullRequestAttempt(
        createPullRequest(),
        createPullRequest(changedAfterOverrides),
        "stale diff",
      );
      const stableRetry = createPullRequest({
        headSha: "retry-head",
        baseSha: "retry-base",
        updatedAt: "2026-08-04T00:01:00Z",
      });
      queuePullRequestAttempt(stableRetry, stableRetry, "stable diff");

      const result = await getPullRequestDiff({
        token: "token",
        owner: "base-owner",
        repo: "base-repo",
        prNumber: 7,
      });

      expect(result).toMatchObject({
        diff: "stable diff",
        headSha: "retry-head",
        baseSha: "retry-base",
      });
      expect(octokitMocks.pullsGet).toHaveBeenCalledTimes(6);
    },
  );

  it("rejects with a generic error when both snapshots are unstable", async () => {
    queuePullRequestAttempt(
      createPullRequest(),
      createPullRequest({ headSha: "changed-head-1" }),
    );
    queuePullRequestAttempt(
      createPullRequest({ headSha: "changed-head-1" }),
      createPullRequest({ headSha: "changed-head-2" }),
    );

    await expect(getPullRequestDiff({
      token: "token",
      owner: "base-owner",
      repo: "base-repo",
      prNumber: 7,
    })).rejects.toThrow(
      "Pull request changed while fetching a stable diff snapshot",
    );
  });

  it("returns a null head repository for a deleted fork without base fallback", async () => {
    const pullRequest = createPullRequest({ headRepository: null });
    queuePullRequestAttempt(pullRequest, pullRequest);

    const result = await getPullRequestDiff({
      token: "token",
      owner: "base-owner",
      repo: "base-repo",
      prNumber: 7,
    });

    expect(result.headRepository).toBeNull();
  });
});

describe("getPullRequestSnapshot", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("normalizes one canonical metadata request without diff media", async () => {
    octokitMocks.pullsGet.mockResolvedValue({ data: createPullRequest() });

    const result = await getPullRequestSnapshot({
      token: "token",
      owner: "base-owner",
      repo: "base-repo",
      prNumber: 7,
    });

    expect(result).toEqual({
      title: "Stable PR",
      url: "https://github.com/base-owner/base-repo/pull/7",
      headSha: "head-sha",
      state: "open",
      merged: false,
    });
    expect(octokitMocks.pullsGet).toHaveBeenCalledOnce();
    expect(octokitMocks.pullsGet).toHaveBeenCalledWith({
      owner: "base-owner",
      repo: "base-repo",
      pull_number: 7,
    });
  });

  it("does not hide snapshot API failures", async () => {
    octokitMocks.pullsGet.mockRejectedValue(new Error("GitHub unavailable"));

    await expect(
      getPullRequestSnapshot({
        token: "token",
        owner: "base-owner",
        repo: "base-repo",
        prNumber: 7,
      }),
    ).rejects.toThrow("GitHub unavailable");
  });
});

describe("getPullRequestHeadInfo", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("normalizes head, lifecycle, and fork metadata from one API response", async () => {
    octokitMocks.pullsGet.mockResolvedValue({
      data: createPullRequest({
        headSha: "fork-head",
        headRepository: { owner: "contributor", repo: "sample-fork" },
        state: "closed",
        merged: true,
      }),
    });

    await expect(
      getPullRequestHeadInfo({
        token: "token",
        owner: "base-owner",
        repo: "base-repo",
        prNumber: 7,
      }),
    ).resolves.toEqual({
      branch: "feature-branch",
      headSha: "fork-head",
      state: "closed",
      merged: true,
      headRepoOwner: "contributor",
      headRepoName: "sample-fork",
      isFork: true,
    });
  });

  it("uses the base repository only when GitHub no longer returns a head repository", async () => {
    octokitMocks.pullsGet.mockResolvedValue({
      data: createPullRequest({ headRepository: null }),
    });

    await expect(
      getPullRequestHeadInfo({
        token: "token",
        owner: "base-owner",
        repo: "base-repo",
        prNumber: 7,
      }),
    ).resolves.toMatchObject({
      headRepoOwner: "base-owner",
      headRepoName: "base-repo",
      isFork: false,
    });
  });

  it("does not hide head metadata API failures", async () => {
    const apiError = new Error("GitHub unavailable");
    octokitMocks.pullsGet.mockRejectedValue(apiError);

    await expect(
      getPullRequestHeadInfo({
        token: "token",
        owner: "base-owner",
        repo: "base-repo",
        prNumber: 7,
      }),
    ).rejects.toBe(apiError);
  });
});

describe("getRepositoryFileTree", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    octokitMocks.reposGetCommit.mockResolvedValue({
      data: { commit: { tree: { sha: "tree-sha" } } },
    });
    octokitMocks.gitGetTree.mockResolvedValue({
      data: {
        tree: [
          { type: "blob", path: "src/file.ts", size: 120 },
          { type: "blob", path: "src/unknown-size.ts" },
          { type: "tree", path: "src" },
          { type: "blob" },
        ],
        truncated: true,
      },
    });
  });

  it("maps exact-commit blob entries and preserves size and truncation", async () => {
    const result = await getRepositoryFileTree({
      token: "token",
      owner: "owner",
      repo: "repo",
      commitSha: "commit-sha",
    });

    expect(octokitMocks.reposGetCommit).toHaveBeenCalledWith({
      owner: "owner",
      repo: "repo",
      ref: "commit-sha",
    });
    expect(octokitMocks.gitGetTree).toHaveBeenCalledWith({
      owner: "owner",
      repo: "repo",
      tree_sha: "tree-sha",
      recursive: "true",
    });
    expect(result).toEqual({
      files: [
        { path: "src/file.ts", size: 120 },
        { path: "src/unknown-size.ts", size: null },
      ],
      truncated: true,
    });
  });

  it("passes one shared signal to both exact-commit requests", async () => {
    const controller = new AbortController();

    await getRepositoryFileTree({
      token: "token",
      owner: "owner",
      repo: "repo",
      commitSha: "commit-sha",
      signal: controller.signal,
    });

    expect(octokitMocks.reposGetCommit.mock.calls[0][0].request.signal).toBe(
      controller.signal,
    );
    expect(octokitMocks.gitGetTree.mock.calls[0][0].request.signal).toBe(
      controller.signal,
    );
  });
});

describe("getFileContent", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("decodes file content without adding a request object when signal is omitted", async () => {
    octokitMocks.reposGetContent.mockResolvedValue({
      data: {
        type: "file",
        content: Buffer.from("source text").toString("base64"),
        sha: "file-sha",
      },
    });

    const result = await getFileContent({
      token: "token",
      owner: "owner",
      repo: "repo",
      path: "src/file.ts",
      ref: "commit-sha",
    });

    expect(result).toEqual({ content: "source text", sha: "file-sha" });
    expect(octokitMocks.reposGetContent.mock.calls[0][0]).not.toHaveProperty("request");
  });

  it("passes the context deadline signal to the contents request", async () => {
    const controller = new AbortController();
    octokitMocks.reposGetContent.mockResolvedValue({
      data: {
        type: "file",
        content: Buffer.from("source text").toString("base64"),
        sha: "file-sha",
      },
    });

    await getFileContent({
      token: "token",
      owner: "owner",
      repo: "repo",
      path: "src/file.ts",
      ref: "commit-sha",
      signal: controller.signal,
    });

    expect(octokitMocks.reposGetContent.mock.calls[0][0].request.signal).toBe(
      controller.signal,
    );
  });

  it("returns null for a 404 response", async () => {
    octokitMocks.reposGetContent.mockRejectedValue(
      Object.assign(new Error("not found"), { status: 404 }),
    );

    await expect(getFileContent({
      token: "token",
      owner: "owner",
      repo: "repo",
      path: "src/missing.ts",
      ref: "commit-sha",
    })).resolves.toBeNull();
  });
});
